### ISSUE TITLE
Signals not added to workspace when using Seq CLI

### ISSUE THREAD

**Issue by prlcutting** [datalust/seq-tickets#1332]
**Describe the bug**
I am trying to use the Seq CLI to automate the creation of a shared workspace, and add a bunch of signals to it.  Perhaps I don't understand how this is supposed to work, but my expectation was that by calling the `seqcli workspace create` command and specifying one or more signal identifiers with `--signal='signal-1'` arguments would both create the workspace, and also add the signals to it without me having to manually click to add each one individually in the UI.

**To Reproduce**
1. Open a Windows Terminal (or whatever).
2. Use the Seq CLI to connect/authenticate with the Seq server.
2. Assume signals with Id's of `signal-1` and `signal-2` already exist.
3. Run `seqcli workspace create --title=foo --description=bar --signal='signal-1' --signal='signal-2' --protected`
4. Open Seq and view workspace.

**Expected behavior**
The workspace should be populated with signals corresponding to `signal-1` and `signal-2`.

**Actual behavior**
The workspace is created, but no signals are added to it.  They have to be added manually through the UI.

**Screenshots**
![image](https://user-images.githubusercontent.com/6989884/134192022-663655f8-592b-4862-9bd9-568361034604.png)

**Environment (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Seq Version: 2021.2.6459
 - Seq CLI Version: 2021.2.464
 - Using Docker: Yes

**Additional context**
n/a

**Related thoughts**
What I'm trying to achieve is standing up a new Seq instance with as much of it automated as possible.  I've already automated the creation of a bunch of signals, and it would be nice if I could add _all_ of them to a workspace without having to list each one individually as an argument, (with their Id's no less, which isn't super user friendly).

**Comment by nblumhardt** [comment]
Hi @prlcutting - thanks for the thoughts and feedback 👍 

We've made some improvements to `seqcli workspace create` in 2021.3; it's not quite out the door, yet, but the `seqcli` binaries are available at:

https://github.com/datalust/seqcli/releases/tag/v2021.3.502-pre

This would end up looking more like:

```
seqcli workspace create --title=foo --description=bar -c signal-1 -c signal-2 --protected
```

I added [some end-to-end tests](https://github.com/datalust/seqcli/blob/v2021.3.502-pre/test/SeqCli.EndToEnd/Workspace/WorkspaceBasicsTestCase.cs) when making those changes to `workspace create`; I didn't spot any obvious bugs in the earlier version, but it's also possible I fixed some.

On your related thought - standing up a new Seq instance - `seqcli template export` and `seqcli template import` might be a nicer experience in the long run. These are also only in the 2021.3 version linked above.

`seqcli template export` produces a set of JSON-like template files for signals, workspaces, and so-on, from an existing Seq instance. It is limited to working well only with shared entities right now, but that shouldn't be a problem for your use case by the sounds of it.

`seqcli template import` then applies those templates to a target Seq instance. It can `--merge` entities by name, but a nicer approach is to edit the template set so that it's an exact representation of only what you want to create (i.e. doesn't duplicate signals like `Warnings`/`Errors` etc.), and then keep a copy of the `.state` file file that the import process creates, so that future changes to the same entities can be reliably applied to the target server.

There's a bit of documentation to write (nearing that time, now!) but the commands themselves should be reasonably self-explanatory. If you give it a shot and need any help, please drop me a line.

**Comment by prlcutting** [comment]
Hi Nick.  Thanks for the feedback and offer of assistance.

Sounds like there are some goodies coming in 2021.3 that will make this workflow a little easier for us, so thanks for that.  I didn't try the new Seq CLI as I worked around my problem manually, but next time we stand up a Seq instance, I'll be sure to try this again.

Thanks again for the detailed response.

**Comment by nblumhardt** [comment]
Great, thanks @prlcutting 👍

**Comment by prlcutting** [comment]
Hi Nick. So, a few months later, we just did a clean install of Seq 2022.1 and used Seq CLI 2022.1.580 to automate parts of it. It appears that the same problem originally reported still exists in these later versions, where the workspace gets created successfully, but the signals are not associated with it. I worked around it the same way by manually adding the signals to the workspace by double-clicking each one in the UI, so not a big deal, but thought I'd let you know that the problem remains in case you wanted to check it out.

**Comment by nblumhardt** [comment]
Thanks @prlcutting - will take another look 👍

**Comment by liammclennan** [comment]
Hi @prlcutting,

I've been looking into this issue for you. So far I have not been able to reproduce a problem (note that I am using 2022.1). 

Can you please confirm that the signals you are specifying are shared?

When you run the `seqcli workspace create ...` command is there any error?

**Comment by nblumhardt** [comment]
Hi again! I'll close this as stale, but if you are still experiencing issues here, please just let us know.
